//@version=5
indicator('XT_CT_QQ Version 2', max_bars_back=2000, overlay=true)

//inp_Amplitude = input(2, title = "Amplitude", type = input.integer)

Lowest_Low = ta.lowest(low, 3)
MA_Low = ta.ema(low, 3)

Highest_High = ta.highest(high, 2)
MA_High = ta.sma(high, 2)

ATR_Half = ta.atr(100) / 2

Next_Trend = 0
Next_Trend := nz(Next_Trend[1], Next_Trend)

Trend = 0
Trend := nz(Trend[1], Trend)

Low_Max = low[1]

Low_Max := nz(Low_Max[1], Low_Max)

High_Min = high[1]
High_Min := nz(High_Min[1], High_Min)

tableColumn = 1
tableRow = 1

Line_HT = close
Line_HT := nz(Line_HT[1], Line_HT)
Arrow_Shift = 0.0
Line_Color = color.gray

shortAlert = false
buyAlert = false


vap = ta.vwap(hlc3)
// plot(vap,color = color.red,style = plot.style_line )

stopLossATR = ta.atr(5)

// plot(vap - stopLossATR)

// CTI_LB Indicator

src = close  // 
sm = input(12, title='Smoothing Period')
cd = input(0.4, title='Constant D')
ebc = input(false, title='Color Bars')
ribm = input(false, title='Ribbon Mode')

// Half of the smoothing period plus one
di = (sm - 1.0) / 2.0 + 1.0
// Coefficients
c1 = 2 / (di + 1.0)
c2 = 1 - c1
c3 = 3.0 * (cd * cd + cd * cd * cd)
c4 = -3.0 * (2.0 * cd * cd + cd + cd * cd * cd)
c5 = 3.0 * cd + 1.0 + cd * cd * cd + 3.0 * cd * cd

// Initial values
i1 = 0.0
i2 = 0.0
i3 = 0.0
i4 = 0.0
i5 = 0.0
i6 = 0.0

// Normalized source
i1 := c1 * src + c2 * nz(i1[1])
i2 := c1 * i1 + c2 * nz(i2[1])
i3 := c1 * i2 + c2 * nz(i3[1])
i4 := c1 * i3 + c2 * nz(i4[1])
i5 := c1 * i4 + c2 * nz(i5[1])
i6 := c1 * i5 + c2 * nz(i6[1])
// CTI
bfr = -cd * cd * cd * i6 + c3 * i5 + c4 * i4 + c5 * i3




// Volume Indicator
RSI_Period = input(3, title='RSI Length')
Rsi = ta.rsi(src, RSI_Period)
SF = input(5, title='RSI Smoothing')
RsiMa = ta.ema(Rsi, SF)


// Stop Loss using ATR Strategy


atr_length = input(14, title='ATR Length')
stopLossPrice4Long = close[0] - ta.atr(atr_length) * 2
stopLossPrice4Short = close[0] + ta.atr(atr_length) * 2


stopLossLong = false
stopLossShort = false
// For Short 
if Next_Trend == 1
    Low_Max := math.max(Low_Max, Lowest_Low)
    if MA_High < Low_Max and close < low[1]
        if bfr < nz(bfr[1]) and vap > close and RsiMa - 50 <= -10
            stopLossShort := true
            Trend := 1
            Next_Trend := 0
            High_Min := Highest_High
            High_Min




// For Long
if Next_Trend == 0
    High_Min := math.min(High_Min, Highest_High)
    if MA_Low > High_Min and close > high[1]
        if bfr > nz(bfr[1]) and vap < open and RsiMa - 50 >= 10
            stopLossLong := true
            Trend := 0
            Next_Trend := 1
            Low_Max := Lowest_Low
            Low_Max




if MA_High < Low_Max and close < low[1]
    if bfr < nz(bfr[1]) and vap > close and RsiMa - 50 <= -10
        High_Min := Highest_High
        shortAlert := true
        buyAlert := false

if MA_Low > High_Min and close > high[1]
    if bfr > nz(bfr[1]) and vap < open and RsiMa - 50 >= 10
        Low_Max := Lowest_Low
        buyAlert := true
        shortAlert := false


// Making Line & Alert indicator

if Trend == 0
    Line_Color := color.green
    if Trend[1] == 0
        Line_HT := math.max(Low_Max, Line_HT[1])
        Line_HT
    if Trend[1] == 1
        Arrow_Shift := -1 * ta.atr(10)
        Arrow_Shift

if Trend == 1
    Line_Color := color.red
    if Trend[1] == 1
        Line_HT := math.min(High_Min, Line_HT[1])
        Line_HT
    if Trend[1] == 0
        Arrow_Shift := 1 * ta.atr(10)
        Arrow_Shift


// plot(Line_HT, color=color.new(Line_Color, 0), linewidth=2, title='X Trend')


if (close < vap)
    buyAlert := false

if (close > vap)
    shortAlert := false



plotshape(shortAlert, 'Short Here', style=shape.arrowdown, size=size.small, location=location.abovebar, color=color.new(color.red, 0), textcolor=color.new(color.white, 0))
// // Ploting the Stop Loss Line for Short
// // plot(stopLossPrice4Short, color = color.red, style = plot.style_linebr, linewidth = 2, title = "Stop Loss ")
shortAlert := false

plotshape(buyAlert, 'Long Here', style=shape.arrowup, size=size.small, location=location.belowbar, color=color.new(color.green, 0),  textcolor=color.new(color.white, 0))
// // Ploting the Stop Loss Line for Long
// // plot(stopLossPrice4Long, color = color.green, style = plot.style_linebr, linewidth = 2, title = "Stop Loss ")
buyAlert := false

